### ISSUE TITLE
Twig Plugin NullPointerException when hovering over twig expression

### ISSUE THREAD

**Issue by Doozer** [pulse00/Twig-Eclipse-Plugin#73]
java.lang.NullPointerException
	at org.eclipse.php.internal.core.compiler.ast.parser.ASTUtils.findMinimalNode(ASTUtils.java:171)
	at org.eclipse.php.internal.core.typeinference.PHPModelUtils.getTypeInString(PHPModelUtils.java:2344)
	at org.eclipse.php.internal.ui.editor.hover.AbstractPHPEditorTextHover.getElementsAt(AbstractPHPEditorTextHover.java:107)
	at org.eclipse.php.internal.ui.editor.hover.PHPDocumentationHover.internalGetHoverInfo(PHPDocumentationHover.java:488)
	at org.eclipse.php.internal.ui.editor.hover.PHPDocumentationHover.getHoverInfo2(PHPDocumentationHover.java:483)
	at org.eclipse.php.internal.ui.editor.hover.BestMatchHover.getHoverInfo2(BestMatchHover.java:132)
	at org.eclipse.php.internal.ui.editor.hover.PHPTextHoverProxy.getHoverInfo2(PHPTextHoverProxy.java:77)
	at org.eclipse.jface.text.TextViewerHoverManager$4.run(TextViewerHoverManager.java:166)

Session Data:
eclipse.buildId=M20130204-1200
java.version=1.7.0_21
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=de_DE
Command-line arguments:  -os win32 -ws win32 -arch x86_64

**Comment by zulus** [comment]
No longer appear
