### ISSUE TITLE
problem occured when opening a twig file

### ISSUE THREAD

**Issue by ravitej91** [pulse00/Twig-Eclipse-Plugin#76]
I installed twig extension and when trying to open a twig file it was having multiple problem dialog box with following errors.
org/eclipse/php/internal/core/util/OutlineFilter

The message in error log is as follows

"Plug-in com.dubture.twig.core was unable to load class com.dubture.twig.core.documentModel.parser.TwigSourceElementRequestorExtension."

stack trace

java.lang.NoClassDefFoundError: org/eclipse/php/core/compiler/PHPSourceElementRequestorExtension
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:788)
	at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.defineClass(DefaultClassLoader.java:188)
	at org.eclipse.osgi.baseadaptor.loader.ClasspathManager.defineClassHoldingLock(ClasspathManager.java:632)
	at org.eclipse.osgi.baseadaptor.loader.ClasspathManager.defineClass(ClasspathManager.java:607)
	at org.eclipse.osgi.baseadaptor.loader.ClasspathManager.findClassImpl(ClasspathManager.java:568)
	at org.eclipse.osgi.baseadaptor.loader.ClasspathManager.findLocalClassImpl(ClasspathManager.java:492)
	at org.eclipse.osgi.baseadaptor.loader.ClasspathManager.findLocalClass(ClasspathManager.java:465)
	at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.findLocalClass(DefaultClassLoader.java:216)
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:395)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:464)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:421)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:412)
	at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.loadClass(DefaultClassLoader.java:107)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.eclipse.osgi.internal.loader.BundleLoader.loadClass(BundleLoader.java:340)
	at org.eclipse.osgi.framework.internal.core.BundleHost.loadClass(BundleHost.java:229)
	at org.eclipse.osgi.framework.internal.core.AbstractBundle.loadClass(AbstractBundle.java:1212)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:174)
	at org.eclipse.core.internal.registry.ExtensionRegistry.createExecutableExtension(ExtensionRegistry.java:905)
	at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:243)
	at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:55)
	at org.eclipse.php.internal.core.compiler.ast.parser.PHPSourceElementRequestor.<init>(PHPSourceElementRequestor.java:80)
	at org.eclipse.php.internal.core.compiler.ast.parser.PHPSourceElementParser.createVisitor(PHPSourceElementParser.java:30)
	at org.eclipse.dltk.core.AbstractSourceElementParser.parseSourceModule(AbstractSourceElementParser.java:32)
	at org.eclipse.php.internal.core.compiler.ast.parser.PHPSourceElementParser.parseSourceModule(PHPSourceElementParser.java:26)
	at org.eclipse.dltk.internal.core.structure.StructureIndexer.indexDocument(StructureIndexer.java:161)
	at org.eclipse.dltk.internal.core.structure.StructureProjectIndexer.doIndexing(StructureProjectIndexer.java:20)
	at org.eclipse.dltk.core.search.indexing.core.AbstractProjectIndexer.indexSourceModule(AbstractProjectIndexer.java:175)
	at org.eclipse.dltk.core.search.indexing.core.SourceModulesRequest.run(SourceModulesRequest.java:75)
	at org.eclipse.dltk.core.search.indexing.AbstractJob.execute(AbstractJob.java:77)
	at org.eclipse.dltk.internal.core.search.processing.JobManager.run(JobManager.java:452)
	at java.lang.Thread.run(Thread.java:724)
Caused by: java.lang.ClassNotFoundException: org.eclipse.php.core.compiler.PHPSourceElementRequestorExtension
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:501)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:421)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:412)
	at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.loadClass(DefaultClassLoader.java:107)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

**Comment by zulus** [comment]
This has been fixed long time ago. Closing.
