### ISSUE TITLE
Exception if file is not in Build Path

### ISSUE THREAD

**Issue by zulus** [pulse00/Twig-Eclipse-Plugin#82]
```
org.eclipse.dltk.core.ModelException: <project root> [in mb] does not exist
	at org.eclipse.dltk.internal.core.ModelElement.newNotPresentException(ModelElement.java:270)
	at org.eclipse.dltk.internal.core.ProjectFragment.getUnderlyingResource(ProjectFragment.java:342)
	at org.eclipse.dltk.internal.core.Openable.getUnderlyingResource(Openable.java:273)
	at org.eclipse.dltk.internal.core.Openable.getUnderlyingResource(Openable.java:273)
	at org.eclipse.dltk.internal.core.AbstractSourceModule.getUnderlyingResource(AbstractSourceModule.java:368)
	at com.dubture.twig.core.codeassist.context.AbstractTwigCompletionContext.isValid(AbstractTwigCompletionContext.java:113)
	at com.dubture.twig.core.codeassist.context.VariableFieldContext.isValid(VariableFieldContext.java:49)
	at com.dubture.symfony.twig.codeassist.context.TemplateVariableFieldCompletionContext.isValid(TemplateVariableFieldCompletionContext.java:41)
	at org.eclipse.php.internal.core.codeassist.contexts.CompletionContextResolver.resolve(CompletionContextResolver.java:116)
	at org.eclipse.php.internal.core.codeassist.PHPCompletionEngine.complete(PHPCompletionEngine.java:96)
	at org.eclipse.php.internal.core.codeassist.PHPCompletionEngine.complete(PHPCompletionEngine.java:63)
	at org.eclipse.dltk.internal.core.Openable$CompletionThread.run(Openable.java:503)
	at org.eclipse.dltk.internal.core.Openable$CompletionThread.run(Openable.java:484)
```

**Comment by zulus** [comment]
Fixed
