### ISSUE TITLE
Dependency issues when installing on Eclipse Mars (4.5.2)

### ISSUE THREAD

**Issue by Amenel** [pulse00/Twig-Eclipse-Plugin#98]
This is to report that the current release (2.0.1.201703151042) cannot be installed on the previous to last version of Eclipse, ie Mars 4.5.2. 

Here is the report one can read in the **Install** window:

    Cannot complete the install because of a conflicting dependency.
      Software being installed: Twig Editor Feature 2.0.1.201703151042 (com.dubture.twig.feature.feature.group 2.0.1.201703151042)
      Software currently installed: PHP Development Tools (PDT) 3.7.0.201602121754 (org.eclipse.php.feature.group 3.7.0.201602121754)
      Only one of the following can be installed at once: 
        PDT Core Plug-in 3.7.0.201602121754 (org.eclipse.php.core 3.7.0.201602121754)
        PDT Core Plug-in 4.3.1.201703301037 (org.eclipse.php.core 4.3.1.201703301037)
        PDT Core Plug-in 3.5.0.201506101710 (org.eclipse.php.core 3.5.0.201506101710)
        PDT Core Plug-in 3.6.0.201509151953 (org.eclipse.php.core 3.6.0.201509151953)
      Cannot satisfy dependency:
        From: Twig Editor Feature 2.0.1.201703151042 (com.dubture.twig.feature.feature.group 2.0.1.201703151042)
        To: org.eclipse.php.core 4.0.0
      Cannot satisfy dependency:
        From: PHP Development Tools (PDT) 3.7.0.201602121754 (org.eclipse.php.feature.group 3.7.0.201602121754)
        To: org.eclipse.php.core [3.7.0.201602121754]

It seems like the Twig editor requires PDT 4.0, which makes the editor incompatible with any version of Eclipse other than Neon and Oxygen.

If one tries to install the current PDT version (I've tried with 4.3.1), the installation goes through but then Mars gets stuck on the splash screen. I found out that this is because it enters a loop that produces this message in the logs:
    !ENTRY org.eclipse.dltk.core 4 4 2017-06-21 19:16:31.877
    !MESSAGE Background Indexer Crash Recovery
    !STACK 0
    java.lang.NoSuchMethodError: org.eclipse.core.runtime.ListenerList.iterator()Ljava/util/Iterator;
      at org.eclipse.dltk.core.search.indexing.IndexManager.notifyIdle(IndexManager.java:523)
      at org.eclipse.dltk.internal.core.search.processing.JobManager.run(JobManager.java:455)
      at java.lang.Thread.run(Thread.java:748)

Maybe that the PDT 4.0 dependency is an oversight? The readme currently states Indigo (3.7.2) as the minimal version.

**Comment by zulus** [comment]
Looks like documentation is outdated :/

Twig Eclipse Plugin until will be rewritten to Oxygen universal text editor, is synced with PDT because use some internal api, that now often changes. PDT 4.0 will work on Mars fine, (see https://wiki.eclipse.org/PDT/Target_Environment) but you have to add correct update site manually: https://wiki.eclipse.org/PDT/Installation
